### ISSUE TITLE
CSS namespace conflict

### ISSUE THREAD

**Issue by hunterd** [DataTables/DateTime#13]
The CSS file should be named  datatables.net-datetime/css/dateTime.dataTables.scss instead of datatables.net-datetime/css/dataTables.dateTime.scss since it cause a namespace conflict with datatables.net-dt/css/dataTables.dataTables.css and since the other CSS files are named according to this convention I guess.

For the moment we can assign a namespace using the "as" keyword like so :

@use 'datatables.net-datetime/css/dataTables.dateTime.scss' as dataTablesDatetime;

**Comment by AllanJard** [comment]
It should actually perhaps just be called `dateTime.scss` since there are files for the specific styling integrations such as Bootstrap, Bulma and others. The current form is correct for the base DataTables file name structure though, which is why it is, the way it is.

I don't understand why it is causing a namespace conflict? Perhaps you can link to a StackBltiz example showing the issue please.

**Comment by hunterd** [comment]
I don't know but every other datatables packages are naming their CSS files in the same pattern :

```
@use 'datatables.net-dt/css/dataTables.dataTables.css';
@use 'datatables.net-buttons-dt/css/buttons.dataTables.css';
@use 'datatables.net-searchbuilder-dt/css/searchBuilder.dataTables.css';
@use 'datatables.net-fixedcolumns-dt/css/fixedColumns.dataTables.css';
@use 'datatables.net-fixedheader-dt/css/fixedHeader.dataTables.css';
@use 'datatables.net-keytable-dt/css/keyTable.dataTables.css';
@use 'datatables.net-responsive-dt/css/responsive.dataTables.css';
@use 'datatables.net-rowgroup-dt/css/rowGroup.dataTables.css';
@use 'datatables.net-rowreorder-dt/css/rowReorder.dataTables.css';
@use 'datatables.net-scroller-dt/css/scroller.dataTables.css';
@use 'datatables.net-select-dt/css/select.dataTables.css';
@use 'datatables.net-staterestore-dt/css/stateRestore.dataTables.css';
```

except for dateTime that using a reverse pattern.

I guess the conflict comes from the fact that the main dataTables.css file is already using the dataTables prefix and that the dateTime file is using this prefix too.

Here is a stackblitz link :
[](https://stackblitz.com/edit/vitejs-vite-zdlza4?file=package-lock.json)

**Comment by hunterd** [comment]
I just read the [set of rules](https://datatables.net/manual/tech-notes/13) and indeed, if the SCSS doesn't apply specifically to a dataTables styling framework it's well formatted. Sorry for the confusion.

However, the @import keyword is now deprecated : [https://sass-lang.com/blog/import-is-deprecated/](https://sass-lang.com/blog/import-is-deprecated/) so I have to use the @use keyword instead. I don't know if in the future, the rules will change to match the new Dart Sass paradigms but for now I guess we will have to use the "as" keyword to define a custom namespace.

**Comment by AllanJard** [comment]
Ah! That is news to me - thanks for the link! Every day is a school day...

Try using `@forward` instead. That appears to import directly into the current scope rather than doing the namespacing: https://stackblitz.com/edit/vitejs-vite-ecsrcq?file=src%2Fstyle.scss .

**Comment by hunterd** [comment]
Thanks I'm still learning thoses new way to work with SCSS too. It seems like it's the good way.
