### ISSUE TITLE
Weid behaviour with Day.js

### ISSUE THREAD

**Issue by Dennis14e** [DataTables/DateTime#8]
The behavior of DateTime with Day.js (v1.8.17 on example page, same behaviour with current v1.11.3) seems to be strange.
This strange behavior can also be seen on the example page: https://datatables.net/extensions/datetime/examples/initialisation/dayjs

**Steps to reproduce:**
1. Open example page
2. Choose date 11. July 2022
3. The input field now says: "11/7/2022", which is correct (based on "format" option)
4. Click on input field
5. Selected date is now 6. November 2022

**or**

1. Open example page
2. The input field says "17/1/2020"
3. Click on input field
4. Selected date is 13. July 2022 (yesterday)

**Comment by AllanJard** [comment]
Fixed here: https://github.com/DataTables/DateTime/commit/19e0e22ad25794d481c034b696f1dfd7cc955e83 .

See [this forum thread](https://datatables.net/forums/discussion/73400/datetime-with-dayjs-behaves-strangely-wrong-format#latest) for more details.
